### ISSUE TITLE
TableCell (View.php) String expected

### ISSUE THREAD

**Issue by dimbslmh** [cambell-prince/frontaccounting-theme-bootstrap#3]
@cambell-prince Page fails to load on exception. This does not occur with the default theme.

Uncaught exception 'Exception' with message 'String expected, '' given' in /var/www/virtual/saygoweb.com/demo/htdocs/frontaccounting/themes/bootstrap/View.php:90

Should this line be commented out or do you have another suggestion?

See: http://demo.saygoweb.com/frontaccounting/gl/manage/gl_account_types.php?

**Comment by cambell-prince** [comment]
I've fixed the bug in the theme, and also in Front Accounting.  I've updated the demo site so the link you gave now works.  BTW, good bug report :-).  The text of the error plus the link to the problem made for a very easy / quick fix.

**Comment by dimbslmh** [comment]
@cambell-prince thanks for the fix.
