### ISSUE TITLE
Class 'ControlRenderer' not found

### ISSUE THREAD

**Issue by ahsan-bilal-786** [cambell-prince/frontaccounting-theme-bootstrap#4]
I am getting this error as I activate this theme.
Class 'ControlRenderer' not found in /var/www/public_html/frontaccounting/themes/bootstrap/theme.php on line 20

**Comment by cambell-prince** [comment]
Are you using one of the releases available on [this page](https://github.com/cambell-prince/frontaccounting-theme-bootstrap/releases)?  This theme will not work with standard front accounting until [this Pull Request](https://github.com/FrontAccountingERP/FA/pull/8) is merged in.

So for now, you need to use one of the releases I've supplied as part of this project.
